name: chattingroom
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  cloud_firestore: ^4.9.2
  cupertino_icons: ^1.0.6
  firebase_analytics: ^10.5.0
  firebase_auth: ^4.10.0
  firebase_core: ^2.16.0
  firebase_storage: ^11.2.7
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  google_fonts: ^6.1.0
  image_cropper: ^5.0.0
  image_picker: ^1.0.4
  pinput: ^3.0.1
  provider: ^6.0.5
  uuid: ^3.0.7
  zego_express_engine: ^3.9.0
  zego_uikit_prebuilt_call: ^3.15.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/

flutter_icons:
  image_path: "assets/icon/icon.png"
  android: true
  ios: true