// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQqYOAI7IDpnpuBmAJrLgkxVB2kEqbWS8',
    appId: '1:599981693953:web:b69e8ff29a8240888cf400',
    messagingSenderId: '599981693953',
    projectId: 'chatroom-60b42',
    authDomain: 'chatroom-60b42.firebaseapp.com',
    storageBucket: 'chatroom-60b42.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB06wgrWHJWZ9HJZguI-rGX87T8apkGpK0',
    appId: '1:599981693953:android:66cb748ed10909288cf400',
    messagingSenderId: '599981693953',
    projectId: 'chatroom-60b42',
    storageBucket: 'chatroom-60b42.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVqBltLyZCWArrft-EwACIiu2ohGt7rJE',
    appId: '1:599981693953:ios:c2f426546d4f63718cf400',
    messagingSenderId: '599981693953',
    projectId: 'chatroom-60b42',
    storageBucket: 'chatroom-60b42.appspot.com',
    iosBundleId: 'com.khalafawy.chatroom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVqBltLyZCWArrft-EwACIiu2ohGt7rJE',
    appId: '1:599981693953:ios:afe15a079dacae8b8cf400',
    messagingSenderId: '599981693953',
    projectId: 'chatroom-60b42',
    storageBucket: 'chatroom-60b42.appspot.com',
    iosBundleId: 'com.khalafawy.chatroom.RunnerTests',
  );
}
